version: '3.1'

services:
  db:
    image: mariadb:11.3
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: arena
      MYSQL_DATABASE: arena
      MYSQL_USER: arena
      MYSQL_PASSWORD: arena
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: codearena
      MINIO_SECRET_KEY: codearena
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

volumes:
  db_data:
  minio_data:
